 use std::fmt::Write;
 use std::io::{self};

fn main() {
	let mut h = String::new();
	println!("Paste input below\n");
        io::stdin().read_line(&mut h).unwrap();
        let mut sw = String::new();
        sw.push('0');        
        if h.len() % 2 != 1 { sw.pop(); sw.push('1'); }
        let mut s = String::new();
	for &c in h.as_bytes() {
		write!(&mut s, "{:02X}", c).expect("err");
		}
	s.pop(); s.pop();//removes added line feed
	println!("\nEncoded:");
	println!("\n{}\n", s.replace(" ", "").to_ascii_lowercase());//encoded output
	println!("Decoded:\n");
	if sw == "1" { 
		println!("(odd length input, will not decode correctly)"); 
		}
	loop {
		if h.len() == 0 { break; }
		let mut x = String::new();
		loop {
			if h.len() == 0 { break; }
			let y = h.remove(0).to_ascii_lowercase();
			if y == '\u{20}' { continue; }
			x.push(y);
			break;
		}
		loop {
			if h.len() == 0 { break; }
			let z = h.remove(0).to_ascii_lowercase();
			if z == '\u{20}' { continue; }
			x.push(z);
			break;
		}
		match x.as_str() { //decoded output
		"00" => { print!("\u{00}"); },
		"01" => { print!("\u{01}"); },
		"02" => { print!("\u{02}"); },
		"03" => { print!("\u{03}"); },
		"04" => { print!("\u{04}"); },
		"05" => { print!("\u{05}"); },
		"06" => { print!("\u{06}"); },
		"07" => { print!("\u{07}"); },
		"08" => { print!("\u{08}"); },
		"09" => { print!("\u{09}"); },
		"0a" => { print!("\u{0a}"); },
		"0b" => { print!("\u{0b}"); },
		"0c" => { print!("\u{0c}"); },
		"0d" => { print!("\u{0d}"); },
		"0e" => { print!("\u{0e}"); },
		"0f" => { print!("\u{0f}"); },
		"10" => { print!("\u{10}"); },
		"11" => { print!("\u{11}"); },
		"12" => { print!("\u{12}"); },
		"13" => { print!("\u{13}"); },
		"14" => { print!("\u{14}"); },
		"15" => { print!("\u{15}"); },
		"16" => { print!("\u{16}"); },
		"17" => { print!("\u{17}"); },
		"18" => { print!("\u{18}"); },
		"19" => { print!("\u{19}"); },
		"1a" => { print!("\u{1a}"); },
		"1b" => { print!("\u{1b}"); },
		"1c" => { print!("\u{1c}"); },
		"1d" => { print!("\u{1d}"); },
		"1e" => { print!("\u{1e}"); },
		"1f" => { print!("\u{1f}"); },
		"20" => { print!("\u{20}"); },
		"21" => { print!("\u{21}"); },
		"22" => { print!("\u{22}"); },
		"23" => { print!("\u{23}"); },
		"24" => { print!("\u{24}"); },
		"25" => { print!("\u{25}"); },
		"26" => { print!("\u{26}"); },
		"27" => { print!("\u{27}"); },
		"28" => { print!("\u{28}"); },
		"29" => { print!("\u{29}"); },
		"2a" => { print!("\u{2a}"); },
		"2b" => { print!("\u{2b}"); },
		"2c" => { print!("\u{2c}"); },
		"2d" => { print!("\u{2d}"); },
		"2e" => { print!("\u{2e}"); },
		"2f" => { print!("\u{2f}"); },
		"30" => { print!("\u{30}"); },
		"31" => { print!("\u{31}"); },
		"32" => { print!("\u{32}"); },
		"33" => { print!("\u{33}"); },
		"34" => { print!("\u{34}"); },
		"35" => { print!("\u{35}"); },
		"36" => { print!("\u{36}"); },
		"37" => { print!("\u{37}"); },
		"38" => { print!("\u{38}"); },
		"39" => { print!("\u{39}"); },
		"3a" => { print!("\u{3a}"); },
		"3b" => { print!("\u{3b}"); },
		"3c" => { print!("\u{3c}"); },
		"3d" => { print!("\u{3d}"); },
		"3e" => { print!("\u{3e}"); },
		"3f" => { print!("\u{3f}"); },
		"40" => { print!("\u{40}"); },
		"41" => { print!("\u{41}"); },
		"42" => { print!("\u{42}"); },
		"43" => { print!("\u{43}"); },
		"44" => { print!("\u{44}"); },
		"45" => { print!("\u{45}"); },
		"46" => { print!("\u{46}"); },
		"47" => { print!("\u{47}"); },
		"48" => { print!("\u{48}"); },
		"49" => { print!("\u{49}"); },
		"4a" => { print!("\u{4a}"); },
		"4b" => { print!("\u{4b}"); },
		"4c" => { print!("\u{4c}"); },
		"4d" => { print!("\u{4d}"); },
		"4e" => { print!("\u{4e}"); },
		"4f" => { print!("\u{4f}"); },
		"50" => { print!("\u{50}"); },
		"51" => { print!("\u{51}"); },
		"52" => { print!("\u{52}"); },
		"53" => { print!("\u{53}"); },
		"54" => { print!("\u{54}"); },
		"55" => { print!("\u{55}"); },
		"56" => { print!("\u{56}"); },
		"57" => { print!("\u{57}"); },
		"58" => { print!("\u{58}"); },
		"59" => { print!("\u{59}"); },
		"5a" => { print!("\u{5a}"); },
		"5b" => { print!("\u{5b}"); },
		"5c" => { print!("\u{5c}"); },
		"5d" => { print!("\u{5d}"); },
		"5e" => { print!("\u{5e}"); },
		"5f" => { print!("\u{5f}"); },
		"60" => { print!("\u{60}"); },
		"61" => { print!("\u{61}"); },
		"62" => { print!("\u{62}"); },
		"63" => { print!("\u{63}"); },
		"64" => { print!("\u{64}"); },
		"65" => { print!("\u{65}"); },
		"66" => { print!("\u{66}"); },
		"67" => { print!("\u{67}"); },
		"68" => { print!("\u{68}"); },
		"69" => { print!("\u{69}"); },
		"6a" => { print!("\u{6a}"); },
		"6b" => { print!("\u{6b}"); },
		"6c" => { print!("\u{6c}"); },
		"6d" => { print!("\u{6d}"); },
		"6e" => { print!("\u{6e}"); },
		"6f" => { print!("\u{6f}"); },
		"70" => { print!("\u{70}"); },
		"71" => { print!("\u{71}"); },
		"72" => { print!("\u{72}"); },
		"73" => { print!("\u{73}"); },
		"74" => { print!("\u{74}"); },
		"75" => { print!("\u{75}"); },
		"76" => { print!("\u{76}"); },
		"77" => { print!("\u{77}"); },
		"78" => { print!("\u{78}"); },
		"79" => { print!("\u{79}"); },
		"7a" => { print!("\u{7a}"); },
		"7b" => { print!("\u{7b}\u{7b}"); },
		"7c" => { print!("\u{7c}"); },
		"7d" => { print!("\u{7d}\u{7d}"); },
		"7e" => { print!("\u{7e}"); },
		"7f" => { print!("\u{7f}"); },
		"80" => { print!("\u{80}"); },
		"81" => { print!("\u{81}"); },
		"82" => { print!("\u{82}"); },
		"83" => { print!("\u{83}"); },
		"84" => { print!("\u{84}"); },
		"85" => { print!("\u{85}"); },
		"86" => { print!("\u{86}"); },
		"87" => { print!("\u{87}"); },
		"88" => { print!("\u{88}"); },
		"89" => { print!("\u{89}"); },
		"8a" => { print!("\u{8a}"); },
		"8b" => { print!("\u{8b}"); },
		"8c" => { print!("\u{8c}"); },
		"8d" => { print!("\u{8d}"); },
		"8e" => { print!("\u{8e}"); },
		"8f" => { print!("\u{8f}"); },
		"90" => { print!("\u{90}"); },
		"91" => { print!("\u{91}"); },
		"92" => { print!("\u{92}"); },
		"93" => { print!("\u{93}"); },
		"94" => { print!("\u{94}"); },
		"95" => { print!("\u{95}"); },
		"96" => { print!("\u{96}"); },
		"97" => { print!("\u{97}"); },
		"98" => { print!("\u{98}"); },
		"99" => { print!("\u{99}"); },
		"9a" => { print!("\u{9a}"); },
		"9b" => { print!("\u{9b}"); },
		"9c" => { print!("\u{9c}"); },
		"9d" => { print!("\u{9d}"); },
		"9e" => { print!("\u{9e}"); },
		"9f" => { print!("\u{9f}"); },
		"a0" => { print!("\u{a0}"); },
		"a1" => { print!("\u{a1}"); },
		"a2" => { print!("\u{a2}"); },
		"a3" => { print!("\u{a3}"); },
		"a4" => { print!("\u{a4}"); },
		"a5" => { print!("\u{a5}"); },
		"a6" => { print!("\u{a6}"); },
		"a7" => { print!("\u{a7}"); },
		"a8" => { print!("\u{a8}"); },
		"a9" => { print!("\u{a9}"); },
		"aa" => { print!("\u{aa}"); },
		"ab" => { print!("\u{ab}"); },
		"ac" => { print!("\u{ac}"); },
		"ad" => { print!("\u{ad}"); },
		"ae" => { print!("\u{ae}"); },
		"af" => { print!("\u{af}"); },
		"b0" => { print!("\u{b0}"); },
		"b1" => { print!("\u{b1}"); },
		"b2" => { print!("\u{b2}"); },
		"b3" => { print!("\u{b3}"); },
		"b4" => { print!("\u{b4}"); },
		"b5" => { print!("\u{b5}"); },
		"b6" => { print!("\u{b6}"); },
		"b7" => { print!("\u{b7}"); },
		"b8" => { print!("\u{b8}"); },
		"b9" => { print!("\u{b9}"); },
		"ba" => { print!("\u{ba}"); },
		"bb" => { print!("\u{bb}"); },
		"bc" => { print!("\u{bc}"); },
		"bd" => { print!("\u{bd}"); },
		"be" => { print!("\u{be}"); },
		"bf" => { print!("\u{bf}"); },
		"c0" => { print!("\u{c0}"); },
		"c1" => { print!("\u{c1}"); },
		"c2" => { print!("\u{c2}"); },
		"c3" => { print!("\u{c3}"); },
		"c4" => { print!("\u{c4}"); },
		"c5" => { print!("\u{c5}"); },
		"c6" => { print!("\u{c6}"); },
		"c7" => { print!("\u{c7}"); },
		"c8" => { print!("\u{c8}"); },
		"c9" => { print!("\u{c9}"); },
		"ca" => { print!("\u{ca}"); },
		"cb" => { print!("\u{cb}"); },
		"cc" => { print!("\u{cc}"); },
		"cd" => { print!("\u{cd}"); },
		"ce" => { print!("\u{ce}"); },
		"cf" => { print!("\u{cf}"); },
		"d0" => { print!("\u{d0}"); },
		"d1" => { print!("\u{d1}"); },
		"d2" => { print!("\u{d2}"); },
		"d3" => { print!("\u{d3}"); },
		"d4" => { print!("\u{d4}"); },
		"d5" => { print!("\u{d5}"); },
		"d6" => { print!("\u{d6}"); },
		"d7" => { print!("\u{d7}"); },
		"d8" => { print!("\u{d8}"); },
		"d9" => { print!("\u{d9}"); },
		"da" => { print!("\u{da}"); },
		"db" => { print!("\u{db}"); },
		"dc" => { print!("\u{dc}"); },
		"dd" => { print!("\u{dd}"); },
		"de" => { print!("\u{de}"); },
		"df" => { print!("\u{df}"); },
		"e0" => { print!("\u{e0}"); },
		"e1" => { print!("\u{e1}"); },
		"e2" => { print!("\u{e2}"); },
		"e3" => { print!("\u{e3}"); },
		"e4" => { print!("\u{e4}"); },
		"e5" => { print!("\u{e5}"); },
		"e6" => { print!("\u{e6}"); },
		"e7" => { print!("\u{e7}"); },
		"e8" => { print!("\u{e8}"); },
		"e9" => { print!("\u{e9}"); },
		"ea" => { print!("\u{ea}"); },
		"eb" => { print!("\u{eb}"); },
		"ec" => { print!("\u{ec}"); },
		"ed" => { print!("\u{ed}"); },
		"ee" => { print!("\u{ee}"); },
		"ef" => { print!("\u{ef}"); },
		"f0" => { print!("\u{f0}"); },
		"f1" => { print!("\u{f1}"); },
		"f2" => { print!("\u{f2}"); },
		"f3" => { print!("\u{f3}"); },
		"f4" => { print!("\u{f4}"); },
		"f5" => { print!("\u{f5}"); },
		"f6" => { print!("\u{f6}"); },
		"f7" => { print!("\u{f7}"); },
		"f8" => { print!("\u{f8}"); },
		"f9" => { print!("\u{f9}"); },
		"fa" => { print!("\u{fa}"); },
		"fb" => { print!("\u{fb}"); },
		"fc" => { print!("\u{fc}"); },
		"fd" => { print!("\u{fd}"); },
		"fe" => { print!("\u{fe}"); },
		"ff" => { print!("\u{ff}"); },
		_ => ()
		}
	x.clear();
	} 
	println!("\n");
  }

